/*
 * Generated by STIR. Do not edit by hand.
 */

#include <sifteo/asset.h>

#pragma once

extern Sifteo::AssetGroup GameAssets;
extern const Sifteo::AssetImage BackgroundY;
extern const Sifteo::AssetImage BackgroundYTwo;
extern const Sifteo::PinnedAssetImage Font;
extern const Sifteo::AssetImage BackgroundXTwo;
extern const Sifteo::PinnedAssetImage Star;
extern const Sifteo::AssetImage BackgroundX;
extern Sifteo::AssetGroup IconAssets;
extern const Sifteo::AssetImage Icon;
extern const Sifteo::AssetTracker Music;
