APP = BlockParty

include $(SDK_DIR)/Makefile.defs

OBJS = $(ASSETS).gen.o BaseGameCube.o BaseGame.o FlipItCube.o FlipItGame.o ShakeCube.o ShakeGame.o ColorMeCube.o ColorMeGame.o  HotCubeCube.o HotCubeGame.o main.o

ASSETDEPS += assets/*.png $(ASSETS).lua
CDEPS += *.h

include $(SDK_DIR)/Makefile.rules